first_name = input("Enter your First Name: ")
last_name = input("Enter your Last Name: ")
middle_name = input("Enter your Middle Name: ")
birthday = input("Enter your Birthday (e.g., YYYY-MM-DD): ")
gender = input("Enter your Gender: ")
address = input("Enter your Address: ")
course = input("Enter your Course: ")
year_level = input("Enter your Year Level: ")

print("\n--- User Information ---")
print(f"First Name: {first_name}")
print(f"Last Name: {last_name}")
print(f"Middle Name: {middle_name}")
print(f"Birthday: {birthday}")
print(f"Gender: {gender}")
print(f"Address: {address}")
print(f"Course: {course}")
print(f"Year Level: {year_level}")
